from mailjet_rest import Client
import os

class EmailSender:
    def __init__(self, config=None):
        api_key = os.getenv('MAILJET_API_KEY')
        api_secret = os.getenv('MAILJET_SECRET_KEY')
        self.sender_email = os.getenv('SENDER_EMAIL') # Functioning as 'From' address
        self.client = Client(auth=(api_key, api_secret), version='v3.1')

    def render_template(self, summaries, date, article_count):
        # Modern HTML Email Template
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <style>
                body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #374151; background-color: #f3f4f6; margin: 0; padding: 0; }}
                .container {{ max-width: 600px; margin: 0 auto; background-color: #ffffff; }}
                .header {{ background-color: #2563eb; color: #ffffff; padding: 30px 20px; text-align: center; }}
                .header h1 {{ margin: 0; font-size: 24px; font-weight: 700; }}
                .meta {{ font-size: 14px; opacity: 0.9; margin-top: 10px; }}
                .content {{ padding: 30px 20px; }}
                .topic-card {{ margin-bottom: 30px; border-bottom: 1px solid #e5e7eb; padding-bottom: 30px; }}
                .topic-card:last-child {{ border-bottom: none; }}
                .topic-header {{ color: #111827; font-size: 20px; font-weight: 600; margin-bottom: 15px; text-transform: capitalize; border-left: 4px solid #2563eb; padding-left: 12px; }}
                .summary-content {{ font-size: 16px; color: #4b5563; }}
                .footer {{ background-color: #f9fafb; padding: 20px; text-align: center; font-size: 12px; color: #9ca3af; border-top: 1px solid #e5e7eb; }}
                a {{ color: #2563eb; text-decoration: none; }}
                strong {{ color: #1f2937; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>Daily Intelligence Briefing</h1>
                    <div class="meta">{date} &bull; {article_count} Topics Analyzed</div>
                </div>
                <div class="content">
        """
        
        for topic, summary in summaries.items():
            # Convert markdown-style headers if present
            formatted_summary = summary.replace("## ", "")
            # Basic markdown to HTML conversion for lists
            formatted_summary = formatted_summary.replace("\n- ", "<br>&bull; ")
            
            html += f"""
            <div class="topic-card">
                <div class="topic-header">{topic}</div>
                <div class="summary-content">
                    {formatted_summary}
                </div>
            </div>
            """
        
        html += """
                </div>
                <div class="footer">
                    <p>Generated by News Agent AI. Sources verified.</p>
                    <p>To unsubscribe, please reply to this email.</p>
                </div>
            </div>
        </body>
        </html>
        """
        return html

    def render_otp_template(self, otp):
        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <style>
                body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #374151; background-color: #f3f4f6; margin: 0; padding: 0; }}
                .container {{ max-width: 600px; margin: 20px auto; background-color: #ffffff; border-radius: 8px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); overflow: hidden; }}
                .header {{ background-color: #2563eb; color: #ffffff; padding: 30px 20px; text-align: center; }}
                .header h1 {{ margin: 0; font-size: 24px; font-weight: 700; }}
                .content {{ padding: 40px 20px; text-align: center; }}
                .otp {{ font-size: 32px; font-weight: bold; color: #2563eb; letter-spacing: 4px; margin: 20px 0; background-color: #eff6ff; padding: 10px 20px; border-radius: 8px; display: inline-block; }}
                .message {{ font-size: 16px; color: #4b5563; margin-bottom: 20px; }}
                .footer {{ background-color: #f9fafb; padding: 20px; text-align: center; font-size: 12px; color: #9ca3af; border-top: 1px solid #e5e7eb; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>Verification Code</h1>
                </div>
                <div class="content">
                    <p class="message">Please use the verification code below to complete your subscription:</p>
                    <div class="otp">{otp}</div>
                    <p class="message">This code will expire in 10 minutes.</p>
                </div>
                <div class="footer">
                    <p>If you didn't request this code, please ignore this email.</p>
                </div>
            </div>
        </body>
        </html>
        """
        return html

    async def send_email(self, subject, html_content, to_email=None):
        recipient = to_email if to_email else os.getenv("RECIPIENT_EMAIL")
        data = {
          'Messages': [
            {
              "From": {
                "Email": self.sender_email,
                "Name": "News Agent"
              },
              "To": [
                {
                  "Email": recipient,
                  "Name": "Subscriber"
                }
              ],
              "Subject": subject,
              "HTMLPart": html_content,
              "TextPart": "Your daily news digest is here."
            }
          ]
        }
        
        try:
            result = self.client.send.create(data=data)
            print(f"Mailjet response: {result.status_code}")
        except Exception as e:
            print(f"Failed to send email via Mailjet: {e}")